version: '3.8'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ayrton
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: conversation-service
    ports:
      - "27017:27017"
    volumes:
      - ./conversa-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #      - ./mongo:/data/db
    networks:
      - mongo-compose-network
  conversation-service:
    image: ayrtonhe/fiap-conversations-service:0.1.0
    ports:
      - 8080:8080
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
  corretor-service:
    image: ayrtonhe/fiap-corretor-service
    ports:
      - 8082:8089
    networks:
      - mongo-compose-network
  cliente-service:
    image: ayrtonhe/fiap-cliente-service
    ports:
      - 8083:8088
    networks:
      - mongo-compose-network
  planos-service:
    image: ayrtonhe/fiap-planos-service
    ports:
      - 8084:8082
    networks:
      - mongo-compose-network
  operadora-service:
    image: ayrtonhe/fiap-operadora-service
    ports:
      - 8085:8081
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    external: true