micronaut:
  application:
    name: conversaService
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
mongodb:
#  host: localhost
#  port: 27017
#  username: ayrton
#  password: 123456
#  database: conversation-service
 uri: mongodb://ayrton:123456@localhost:27017/conversation-service